Lesson6
40grivenprog/qna pull request #3
Opened 2020-09-09 11:15 UTC by 40grivenprog

2020-09-09 14:25 UTC, IvanShamatov requested changes

2020-09-09 14:25 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @answer.user_id = current_user.id
Это валидный код, но чаще практикуется вариант, когда все параметры для создания ответа собираются в одном месте
`@answer = @question.answers.new(answer_params.merge(user: current_user))`

2020-09-09 14:25 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    if current_user.authored_answer? @answer
Тут есть несколько поинтов:
1. Как правило User -- самая нагруженная и самая монструозная модель во всем проекте. Именно на юзера завязана чуть ли не вся логика приложения. Поэтому, совсем не круто дополнять её методами, которые проверяют каждый из релейшнов. 
2. Тут можно было бы инвертировать логику: спросить у "ответа", кто его автор и эквивалентен ли он текущему пользователю. И этим мы точно бы разгрузили модель пользователя, но так ли нам нужно знать, что пользователь, который удаляет является автором? 
3. На самом деле нет. Нам нужно знать, что нужная запись в базе смогла быть удаленной или нет.

```ruby
answer = current_user.answers.find_by(id: params[:id])
if answer.destroy
  ...
else
  ...
end

```
В данном варианте мы проверяем что был найден ответ среди ответов именно этого пользователя с таким айдишником, и если он удалился нормально, то значит все в порядке.

2020-09-09 14:25 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +      redirect_to questions_path, notice: 'Destroyed succesfully'
successfully

2020-09-09 14:25 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +  before_action :find_answer, only: %i[show destroy]
выглядит так, как будто new и show в этом контроллере и вовсе не нужны, если они показываются в рамках странички вопроса

2020-09-09 14:25 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    @question.user_id = current_user.id
`@question = current_user.questions.new(question_params)` сразу создаст инстанс вопроса этого пользоваля с помощью релейшна, который был объявлен в модели

2020-09-09 14:25 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    if current_user.authored_question? @question
см объяснение и логику в AnswersController'e

2020-09-09 14:25 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +      redirect_to questions_path, alert: 'You are not the author'
Обрати внимание, что мы делаем редирект на одну и ту же страницу в любом случае, различается лишь мессадж. Можно ли это как-то унифицировать?

2020-09-09 14:25 UTC, IvanShamatov commented on app/models/user.rb
> +  has_many :answers
Интересно, если мы хотим удалять вопросы при удалении пользователя, то как поведут себя ответы, если вдруг id, на который они ссылаются перестанет существовать? Приложение покрашится, причем покрашится оно вовсе не в момент отрисовки ответа, а при попытке удаления юзера.

2020-09-09 14:25 UTC, IvanShamatov commented on app/models/user.rb
> +    questions.include? resource
хоть я выше и упоминал, что этот метод не нужен, но я объясню огромнейшую проблему, которая кроется за этой строчкой. 
метод include? не является рельсовым, а является рубишным. Что это означает для нас? каждый раз, когда будет вызван этот метод, ты пойдешь в базу, достанешь из базы все рекорды этого пользоваля, создашь их в памяти, а потом как по массиву пробежишься по каждому, чтобы узнать, не является ли этот объектом идентичным ресурсу.

Если у тебя 10 вопросов и 10 пользователей -- проблем нет. Но если у тебя 10к пользователей с 10к вопросами каждый полезет в базу что-то удалять, то мы инстанцируем в память 100м записей и просто сожрем всю память на сервере. Ситуация маловероятная для этого конкретного сценария, но если все приложение будет такими штуками утыкано, то беды не избежать

Что можно сделать? Проверять просто в базе, запросом в базу, есть ли такая запись с таким айдишником или нет. И максимум что ты получишь в результате это true/false

`questions.exists?(user_id: resource.id)`

2020-09-09 14:25 UTC, IvanShamatov commented on app/views/answers/_answer.html.slim
> += answer.body if answer
подскажи, пожалуйста, почему ты проверяешь наличие ответа в каждой строчке, его может здесь не быть?

2020-09-09 14:25 UTC, IvanShamatov commented on app/views/answers/_answer.html.slim
> += answer.body if answer
А что если у нас вьюшка на ответ будет не 2 строчки, а 100 строчек, в каждой тоже будет проверка if answer?

2020-09-09 14:25 UTC, IvanShamatov commented on app/views/answers/index.html.slim
> += render @answers
Перенос строки в конце каждого файла должен быть. Посмотри в настройках редактора, это должно быть выставлено автоматически, чтобы при каждом сохранении прописывался корректный для POSIX систем EOF (end of file)

2020-09-09 14:25 UTC, IvanShamatov commented on app/views/answers/show.html.slim
> += @answer.body
см выше

2020-09-09 14:25 UTC, IvanShamatov commented on app/views/answers/_new.html.slim
> +=render 'shared/errors', resource: @answer
кстати, если глянуть по пиару дальше, то там будет еще один паршл для ошибок (от девайса), может один какой-нибудь будем использовать? (это не критично, но зато все ошибки всегда будут выглядеть одинаково)

2020-09-09 14:25 UTC, IvanShamatov commented on app/views/questions/show.html.slim
> +
согласно заданию здесь где-то должны быть еще ответы на этот вопрос

2020-09-09 14:25 UTC, IvanShamatov commented on spec/controllers/answers_controller_spec.rb
> +       expect { delete :destroy, params: { id: answer }}.to change(Answer, :count).by(-1)
не хватает проверки на логику, что удалить может только автор

2020-09-09 14:25 UTC, IvanShamatov commented on spec/controllers/questions_controller_spec.rb
> +       expect { delete :destroy, params: { id: question }}.to change(Question, :count).by(-1)
аналогично и здесь

2020-09-09 14:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        redirect_to @answer
следующий комментарий относится к этой строке ))

2020-09-09 14:37 UTC, vkurennov commented on spec/features/answer/answer_spec.rb
> +feature 'User can delete an answer if user is an author', %q{
каждую фичу надо описывать в отдельном файле

2020-09-10 08:15 UTC, IvanShamatov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to question_path question
лучше расставлять скобки все же, потому что от версии к версии руби этот код может перестать работать

2020-09-10 08:15 UTC, IvanShamatov commented on spec/features/answer/destroy_answer_spec.rb
> +end
EOF, поправь, пожалуйста, в редакторе своем

2020-09-10 08:15 UTC, IvanShamatov commented on spec/models/user_spec.rb
> +  it { should have_many(:answers) }
депенд изменил, а спек забыл исправить. Если бы следовал принципу "сначала тесты", то код бы изменился в результате спек, а не наоборот

2020-09-10 08:16 UTC, vkurennov requested changes

2020-09-10 08:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path @question
можно просто `redirect_to @question`, ну и если несколько методов идут в цепочке, то нужно аргументы у второго и последующего в скобки заключать

2020-09-10 08:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
1. Лучше сравнивать по user_id, так не будет лишнего запроса к базе
2. Такая проверка много еще где потребуется, поэтому все же метод в модели User стоит написать, но написать один универсальный метод, `User#author_of?`, который принимает объект и возвращать true/false в зависимости от того, автор это или нет. И не забудь тесты модели на этот метод написать

2020-09-10 08:16 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Замени на вызов `User#author_of?`

2020-09-10 08:16 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> += button_to  'Delete', answer_path(answer), method: :delete
зачем показывать ссылку на удаление всем подряд? показывай только автору

2020-09-10 08:16 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +ruby: end
при использовании синтаксиса, указанного выше,  end ставить не нужно

2020-09-10 08:16 UTC, vkurennov commented on app/views/answers/_new.html.slim
> += form_with scope: :answer, url: question_answers_path(@question), local: true do |f|
лучше для вложенных ресурсов задавать путь через массив: 

`form_with model: [@question, @answer]`

2020-09-10 08:16 UTC, vkurennov commented on app/views/questions/_question.html.slim
> += button_to  'Delete', question_path(question), method: :delete
эту ссылку тоже стоит показывать только автору

2020-09-10 08:16 UTC, vkurennov commented on app/views/shared/_navbar.html.slim
> += link_to 'Log Out', destroy_user_session_path, method: :delete
стоит показать ссылку на вход, если юзер не залогинен

2020-09-10 08:16 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid params' do
тут еще нужен тест, проверяющий, что устанавливается связь между ответом и залогиненным юзером

2020-09-10 08:16 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +         expect { delete :destroy, params: { id: answer }}.to change(Answer, :count).by(0)
лучше `not_to change(...)`

2020-09-10 08:16 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid params' do
тут нужно проверить, что устанавливается связь с залогиненным юзером

2020-09-10 08:16 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +         expect { delete :destroy, params: { id: question }}.to change(Question, :count).by(0)
`not_to change(...)`

2020-09-10 08:16 UTC, vkurennov commented on spec/features/answer/answer_spec.rb
> +    scenario 'write an answer with valid params' do
здесь лучше не обращаться к фабрикам, а какую-то конкретную строку задать и ее же проверить, во избежание неявных ошибок

2020-09-10 08:16 UTC, vkurennov commented on spec/features/answer/destroy_answer_spec.rb
> +      expect(page).to have_content('Destroyed successfully')
тут еще надо проверить, что после удаления на странице нет удаленного ответа

2020-09-10 08:16 UTC, vkurennov commented on spec/features/answer/destroy_answer_spec.rb
> +      click_on 'Delete'
лучше не показывать ссылку на удаление не-автору и это и проверить в тесте

2020-09-10 08:16 UTC, vkurennov commented on spec/features/answer/destroy_answer_spec.rb
> +    click_on 'Delete'
тут тоже лучше не показывать ссылку

2020-09-10 08:16 UTC, vkurennov commented on spec/features/question/destroy_question_spec.rb
> +      click_on 'Delete'
лучше не показывать ссылку

2020-09-11 10:30 UTC, vkurennov approved these changes

2020-09-11 10:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params.merge(user_id: current_user.id))
тут, кстати, красивее было бы работать с ассоциацией user, а не с user_id. а вот при сравнении лучше работать с user_id, чтобы запрос лишний не делать

2020-09-11 10:30 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +- if answer.valid?
тут лучше заменить проверку на `answer.persisted?`, чтобы не выполнять еще раз валидацию для каждого ответа.

2020-09-11 10:30 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    = button_to  'Delete', answer_path(answer), method: :delete if current_user.author_of? answer rescue nil
вот такие конструкции очень сложно читаются, вынести здесь if перед button, тогда и rescue не нужен будет и читаться код будет проще. в видах вообще постфиксные условия лучше не использовать, их не видно, код сложнее воспринимается.

2020-09-11 10:30 UTC, vkurennov commented on app/views/questions/_question.html.slim
> += button_to  'Delete', question_path(question), method: :delete if current_user.author_of? question rescue nil
тут тоже стоит использовать префиксную форму if (условие перед телом)

2020-09-11 10:30 UTC, vkurennov commented on spec/models/user_spec.rb
> +  it 'is expected that user author_of? method works correct' do
ну если у нас условие, то всегда надо тестировать оба варианта - и когда оно выполняется и когда нет, т.е. на false тоже нужен тест.

2020-09-11 10:30 UTC, vkurennov commented on spec/models/user_spec.rb
> +   expect(user.author_of?(question)).to be true
лучше так: `expect(user).to be_author_of(question)`

работает для любых методов-предикатов: пернеосим вызов метода после to, добавляем к имени be_ и убираем знак вопроса

2020-09-11 14:05 UTC, merged