Задание к уроку "Протокол OAuth"
40grivenprog/qna pull request #9
Opened 2020-11-23 19:21 UTC by 40grivenprog

Реализовать аутентификацию через Github и любой другой соц. сети, на выбор (Twitter, VK и т.п.). 
Обязательно покрыть acceptance и unit-тестами (как тестировать описано в доп. материалах к уроку).

2020-12-19 10:35 UTC, IvanShamatov requested changes
правки косметические, и с усложненным заданием справился, поэтому считаю, что как раз можно взять и воткнуть CI, например github actions

2020-12-19 10:35 UTC, IvanShamatov commented on app/models/user.rb
> +  def create_authorization(auth)
этот метод нужен в сервисе, откуда он вызвается,нет смысла класть этот метод в модель

2020-12-19 10:35 UTC, IvanShamatov commented on app/models/user.rb
> +    FindForOauthService.new(auth).call
этот сервис можно вызывать напрямую оттуда, где используется метод модели, и при этом удалить связность между моделью и сервисом. На живых проектах сервисов огромное количество, исчисляется сотнями, нет никакой необходимости делать методы из модели, чтобы дергать сервисы

2020-12-19 10:35 UTC, IvanShamatov commented on app/services/find_for_oauth_service.rb
> +  def new_user_with_email(email)
ну вот ты метод этот же здесь вынес, зачем же create_authorization в модели сделал, а не тут

2020-12-19 10:35 UTC, IvanShamatov commented on spec/controllers/oauth_callbacks_controller_spec.rb
> +                                                                                    }) }
очень странный отступ, я бы порекомендовал прогнать файл рубокопом и посмотреть, как он заавтолинтит тебе

2021-04-05 10:25 UTC, vkurennov approved these changes

2021-04-06 18:20 UTC, merged